### ISSUE TITLE
Name based on PR number

### ISSUE THREAD

**Issue by mgkimsal** [mehrancodes/veyoze#47]
Was going to try a PR back to this to help with what I need more of...

The notion of naming based on the text in a branch can be handy, but it may vary widely, and you're dealing with regexing characters and truncation, etc.

For situations where there's a PR, the PR *number* from github would be more ... uniform/stable.  I'll know what the deployed domain name is regardless of branch naming rules.  

Also, I'm working in a scenario where I don't have any easy way to determine *what* a deployed name will be without manually going to the GH action run and viewing the output.

For PR builds, knowing that PR-15 will be pr-15.domain.com, etc... would be helpful.

You can't do this with the current setup because we need the github.ref_name (which may look like 178/merge, for example).  Pulling that out, then prefixing "pr-"... would be useful.  

Noodle on this.  If you have a standard/quick way of doing this with current setup, that'd be great, but I think the info is just... not there.

A 'before' job

```
  variables:
    outputs:
      tag_name: ${{ steps.var.outputs.branch_name}}
    runs-on: "ubuntu-latest"
    steps:
      - name: Setting global variables
        uses: actions/github-script@v6
        id: var
        with:
          script: |
            core.setOutput('branch_name', 'pr-${{ github.ref_name }}'.split('/').shift());
```

This creates a pr-XYZ environment value that can be picked up in next job

```
  veyoze-provision:
    needs: [ 'variables' ]
    runs-on: ubuntu-latest
...
          FORGE_DOMAIN: ${{ needs.variables.outputs.tag_name }}.mydomain.com
```

but... this doesn't work (and I'm not sure why 'tag_name' is in 'outputs' when it should be 'branch_name' from the previous job, but whatever...)

You'd need to have a separate 

FORGE_PREFIX = ${{ needs.variables.outputs.tag_name }}

and then work with that (perhaps... if FORGE_PREFIX exists, use that, otherwise fall back to the existing code?)
or...

FORGE_GIT_REF={{github.ref_name}}
and do more PHP processing?
